package com.model;

/**
 * Data Model Class for Silver Bar Order.
 * Could provide a Builder in future versions 
 * @author panigs
 *
 */
public class SilverBarOrder {
	/** userId of the user who placed/registered the order. 
	 * Could be an UserId type as well. 
	 * But for simplicity used String to match provided examples.
	 */
	String userId; 
	
	/** quantity of the order. 
	 * We could ask the question to Business Desk how big the quantity could be.
	 * For this exercise double is chosen for simplicity
	 */
	double quantity;
	
	/** Price at which is the order is place/registered
	 * Ideally should be currency and value.
	 * The value should be BigDecimal instead of float/double
	 * as we need to perform equal operation to merge orders with same price.
	 * However its kept simple with Integer (to match with the examples provided).
	 * Integer as it be using it in a map as key (for internal Cache)
	 */	
	Integer price;
	
	/**OrderType, if Buy or Sell.
	 * 
	 */
	SilverBarOrderTypeEnum type;
	
	/** Order Id, should be unique for each order.
	 * Could be a Custom type, with a OrderId generation service.
	 * Keeping it simple as Integer. 
	 * Integer so that it can be store in a map for in memory solution
	 * so that it could queried on order id to get the order.
	 * 
	 * Null value means not a valid order and can be used as a container to merge order.
	 * again keeping it simple instead of creating a new merged order type.
	 * 
	 * The Id will be generated by the server on creation of the new order.
	 */	
	Integer id;
	
	/**
	 * Status of the Order if Live or Cancelled
	 */
	SilverBarOrderStatusEnum status;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public double getQuantity() {
		return quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	public Integer getPrice() {
		return price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public SilverBarOrderTypeEnum getType() {
		return type;
	}

	public void setType(SilverBarOrderTypeEnum type) {
		this.type = type;
	}

	public Integer getOrderId() {
		return id;
	}

	public void setOrderId(Integer orderId) {
		this.id = orderId;
	}

	public SilverBarOrderStatusEnum getStatus() {
		return status;
	}

	public void setStatus(SilverBarOrderStatusEnum orderStatus) {
		this.status = orderStatus;
	}
	
	//we have assumed only one currency, £
	public String toString() {
		return String.format("%s %.2fkg for £%d", type.toString(), quantity, price ); 
	}

	public SilverBarOrder(String userId, double quantity, Integer price, SilverBarOrderTypeEnum type, Integer id,
			SilverBarOrderStatusEnum status) {
		super();
		this.userId = userId;
		this.quantity = quantity;
		this.price = price;
		this.type = type;
		this.id = id;
		this.status = status;
	}
}
